web:
  image: patriceckhart/docker-neos-alpine
  ports:
    - '80'
    - '22:22'
  links:
    - mariadb:mariadb
  volumes:
    - /data
  environment:
    # If you use a GITHUB_TOKEN, just enter YourGitRepo.git as GITHUB_REPOSITORY
    - GITHUB_REPOSITORY=https://github.com/yourgitaccount/YourGitRepo
    # - GITHUB_REPOSITORY=YourGitRepo.git
    #- GITHUB_TOKEN=9a72f0aca3c52463b17464k2277833x58037ff68
    - GITHUB_USERNAME=yourgitusername
    # When using the following ENV, a database and a privileged user must already be created, otherwise the container will crash
    - DB_DATABASE=neos
    - DB_USER=admin
    - DB_PASS=pass
    - DB_HOST=mariadb
    # Neos CMS site import
    - SITE_PACKAGE=Your.Site
    # Neos CMS User
    - ADMIN_PASSWORD=password
    #- CONTAINERNAME=yourneos
    #- VIRTUAL_HOST=dev.neos.local

mariadb:
  image: mariadb:latest
  expose:
    - 3306
  volumes:
    - /var/lib/data
  environment:
    MYSQL_DATABASE: 'neos'
    MYSQL_USER: 'admin'
    MYSQL_PASSWORD: 'pass'
    MYSQL_ROOT_PASSWORD: 'root'
  ports:
    - '3306:3306'
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci