nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - '80:80'
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

db:
  image: mariadb:latest
  expose:
    - 3306
  volumes:
    - /var/lib/data
  environment:
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'admin'
    MYSQL_PASSWORD: 'pass'
    MYSQL_ROOT_PASSWORD: 'root'
  ports:
    - '3306:3306'
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

web:
  build: .
  ports:
    - '80'
    - '22'
  links:
    - db:db
  volumes:
    - /data
    #- ./Configuration:/data/neos/Configuration
    #- ./Data/Logs:/data/neos/Data/Logs
    #- ./Data/Persistent/Resources:/data/neos/Data/Persistent/Resources
    #- ./Packages/Sites:/data/neos/Packages/Sites
    # for Development on Mac
    #- ./data:/data:cached
  environment:
    #- GITHUB_REPOSITORY=https://github.com/patriceckhart/Inoovum-NeosFlow-Boilerplate
    #- GITHUB_REPOSITORY=https://github.com/patriceckhart/Inoovum-NeosCMS-Boilerplate
    - GITHUB_REPOSITORY=https://github.com/patriceckhart/NeosCMS-Boilerplate.git
    #- GITHUB_REPOSITORY=https://inoovum@github.com:inoovum/InoovumBoilerplate
    #
    # For public repositories do that
    #- GITHUB_REPOSITORY=https://github.com/inoovum/InoovumBoilerplate.git
    #
    # For private repositories do that
    #- GITHUB_REPOSITORY=InoovumAccountDistribution.git
    #- GITHUB_USERNAME=inoovum
    #- GITHUB_TOKEN=sdfsdf
    #- GITHUB_USERNAME=inoovum
    - GITHUB_USERNAME=patriceckhart
    # When using the following ENV, a database and a privileged user must already be created, otherwise the container will crash
    #- DB_DATABASE=db
    #- DB_USER=admin
    #- DB_PASS=pass
    #- DB_HOST=db
    # Neos CMS site import
    #- SITE_PACKAGE=Inoovum.Site
    #- SITE_PACKAGE=Raw.Site
    # Neos CMS User
    #- ADMIN_PASSWORD=password
    #- EDITOR_USERNAME=editor
    #- EDITOR_PASSWORD=editor
    #- EDITOR_FIRSTNAME=Editor
    #- EDITOR_LASTNAME=User
    #- EDITOR_ROLE=My.Package:MyEditor
    #- BASE_URI=http://localhost/
    #- CONTAINERNAME=web
    - VIRTUAL_HOST=dev.test2.loc