web:
  build: .
  ports:
    - '80:80'
    - '22:22'
  links:
    - db:db
  volumes:
    - /data
  environment:
    #- GITHUB_REPOSITORY=https://github.com/patriceckhart/Inoovum-NeosFlow-Boilerplate
    #- GITHUB_REPOSITORY=https://github.com/patriceckhart/Inoovum-NeosCMS-Boilerplate
    - GITHUB_REPOSITORY=https://github.com/patriceckhart/NeosCMS-Boilerplate.git
    - GITHUB_USERNAME=patriceckhart
    - ADMIN_PASSWORD=admin
    - EDITOR_USERNAME=editor
    - EDITOR_PASSWORD=editor
    - EDITOR_FIRSTNAME=Max
    - EDITOR_LASTNAME=Mustermann
    
db:
  image: mariadb:latest
  expose:
    - 3306
  volumes:
    - /var/lib/data
  environment:
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'admin'
    MYSQL_PASSWORD: 'pass'
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'