Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%env:DB_DATABASE%'
        user: '%env:DB_USER%'
        password: '%env:DB_PASS%'
        host: '%env:DB_HOST%'
    http:
      baseUri: '%env:BASE_URI%'
  Imagine:
    driver: Imagick